# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4495e185d5734ad900534e13715def312c9b26cda2ad3397ccdf319ce94e00e8d53519a677c886df57c089aa5e1f24d21e5eb69496335555d922392abad930

test:
  secret_key_base: f5df25198cee15c1b6a1306903b945d1a33edb1c4ec8493142bdd4f3bab9f687785fbb5f89072f1906b87dc270c8d96e6a253fcf146d79c6dffb3cec02a33a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
